/**
 * Decorate the event block.
 * Handles both list-view cards and detail-view pages generated by JSON2HTML.
 * @param {Element} block the block element
 */
export default function decorate(block) {
  const container = document.createElement('div');
  container.className = 'event-container';

  // Extract heading — could be h1 (detail), h2, or h3 (list card)
  const heading = block.querySelector('h1, h2, h3');
  if (heading) {
    heading.classList.add('event-heading');
  }

  // Extract image, falling back when it is absent or fails to load.
  const imageWrapper = document.createElement('div');
  imageWrapper.className = 'event-image';
  const showImageFallback = () => {
    imageWrapper.classList.add('event-image-placeholder');
    imageWrapper.replaceChildren('No Image Found');
    imageWrapper.setAttribute('role', 'img');
    imageWrapper.setAttribute('aria-label', 'No image found');
  };

  const picture = block.querySelector('picture');
  const image = picture?.querySelector('img') || block.querySelector('img');
  if (picture) {
    imageWrapper.append(picture);
  } else if (image) {
    imageWrapper.append(image);
  }

  if (image) {
    image.addEventListener('error', showImageFallback, { once: true });
    if (image.complete && image.naturalWidth === 0) showImageFallback();
  } else {
    showImageFallback();
  }
  container.append(imageWrapper);

  // Extract body content (everything after the image row)
  const bodyWrapper = document.createElement('div');
  bodyWrapper.className = 'event-body';

  // Get the content cells — the block has rows with div > div structure
  const rows = [...block.querySelectorAll(':scope > div')];
  rows.forEach((row) => {
    const cells = [...row.children];
    cells.forEach((cell) => {
      // Skip cells that only contained the picture (already moved)
      if (cell.children.length === 0 && cell.textContent.trim() === '') return;
      if (cell.querySelector('picture') && cell.children.length === 1) return;

      // Move remaining content to body
      while (cell.firstChild) {
        bodyWrapper.append(cell.firstChild);
      }
    });
  });

  bodyWrapper.querySelectorAll('img').forEach((bodyImage) => {
    const removeBrokenImage = () => bodyImage.remove();
    bodyImage.addEventListener('error', removeBrokenImage, { once: true });
    if (bodyImage.complete && bodyImage.naturalWidth === 0) removeBrokenImage();
  });

  container.append(bodyWrapper);

  // Replace block content with reorganized structure
  block.textContent = '';
  block.append(container);
}
